### Create a new patient entity
POST http://lb-eb6f468b.elb.localhost.localstack.cloud:4000/patients
Content-Type: application/json

{
  "name": "Pooja4 Laxman Lengare",
  "email": "pooja4@gmail.com",
  "address": "Baner, Pune",
  "dateOfBirth": "1999-10-13",
  "registeredDate": "2024-01-14"
}

###