### Updates a new patient entity
PUT http://lb-eb6f468b.elb.localhost.localstack.cloud:4000/patients/97229456-e1f2-409f-bf08-a8d63510d316
Content-Type: application/json

{
  "name": "Pradip Laxman Lengare",
  "email": "pradip@gmail.com",
  "address": "Baner, Pune",
  "dateOfBirth": "1999-10-13"
}

###